version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    target-branch: develop
    ignore:
      - dependency-name: org.objenesis:objenesis
        versions:
          - "> 2.6"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: develop