# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Docker Build

on:
  push:
    branches:
      - 4.x

  pull_request:
    branches:
      - 4.x

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}
      MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
      MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
      GITHUB_TOKEN: ${{ secrets.NITRITE_GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build . \
          --build-arg PGP_KEY_PASSWORD=$PGP_KEY_PASSWORD \
          --build-arg GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
          --build-arg PGP_KEY_ID=$PGP_KEY_ID \
          --build-arg MAVEN_USERNAME=$MAVEN_USERNAME \
          --build-arg MAVEN_PASSWORD=$MAVEN_PASSWORD \
          --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
          /